# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gripper.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gripper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgripper.proto\x12\x10grabette.gripper\"\x0f\n\rStreamRequest\"|\n\x0cGripperFrame\x12\x11\n\tjpeg_data\x18\x01 \x01(\x0c\x12\x31\n\x0bmotor_state\x18\x02 \x01(\x0b\x32\x1c.grabette.gripper.MotorState\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x01\x12\x10\n\x08sequence\x18\x04 \x01(\x04\">\n\nMotorState\x12\x17\n\x0fmotor1_position\x18\x01 \x01(\x02\x12\x17\n\x0fmotor2_position\x18\x02 \x01(\x02\"8\n\x0cMotorCommand\x12\x13\n\x0bmotor1_goal\x18\x01 \x01(\x02\x12\x13\n\x0bmotor2_goal\x18\x02 \x01(\x02\"6\n\x14MotorCommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\r\n\x0bPingRequest\"6\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x02 \x01(\x01\x32\x85\x02\n\x0eGripperService\x12P\n\x0bStreamState\x12\x1f.grabette.gripper.StreamRequest\x1a\x1e.grabette.gripper.GripperFrame0\x01\x12Z\n\x10SendMotorCommand\x12\x1e.grabette.gripper.MotorCommand\x1a&.grabette.gripper.MotorCommandResponse\x12\x45\n\x04Ping\x12\x1d.grabette.gripper.PingRequest\x1a\x1e.grabette.gripper.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gripper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=35
  _globals['_STREAMREQUEST']._serialized_end=50
  _globals['_GRIPPERFRAME']._serialized_start=52
  _globals['_GRIPPERFRAME']._serialized_end=176
  _globals['_MOTORSTATE']._serialized_start=178
  _globals['_MOTORSTATE']._serialized_end=240
  _globals['_MOTORCOMMAND']._serialized_start=242
  _globals['_MOTORCOMMAND']._serialized_end=298
  _globals['_MOTORCOMMANDRESPONSE']._serialized_start=300
  _globals['_MOTORCOMMANDRESPONSE']._serialized_end=354
  _globals['_PINGREQUEST']._serialized_start=356
  _globals['_PINGREQUEST']._serialized_end=369
  _globals['_PINGRESPONSE']._serialized_start=371
  _globals['_PINGRESPONSE']._serialized_end=425
  _globals['_GRIPPERSERVICE']._serialized_start=428
  _globals['_GRIPPERSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
